# Generated by Django 4.2.3 on 2023-08-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id_Usuario',
        ),
    ]
