# Generated by Django 4.2.3 on 2023-08-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_Usuario',
            new_name='id_usuario',
        ),
    ]
